name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        
    - name: Set up Maven
      uses: actions/setup-java@v2
      with:
        java-version: '3.x'
        maven-version: '3.x'
        
    - name: Download Sonar Scanner
      run: |
        curl -sSLo sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.6.0.2311-linux.zip
        unzip -q sonar-scanner.zip -d /opt
        export PATH="$PATH:/opt/sonar-scanner-4.6.0.2311-linux/bin"
        
    - name: Git checkout
      run: git checkout main
      
    - name: Maven compile
      run: mvn clean compile -DskipTests=true
      
    - name: OWASP scan
      run: |
        # Run OWASP Dependency Check
        # Add commands for scanning here
        # Example:
        # dependency-check --scan .
        # mvn org.owasp:dependency-check-maven:5.2.2:check
        
    - name: SonarQube
      run: |
        sonar-scanner \
          -Dsonar.projectName=Devops-Shopping-Cart \
          -Dsonar.java.binaries=.
          -Dsonar.projectKey=Devops-Shopping-Cart
          
    - name: Maven build
      run: mvn clean package -DskipTests=true
      
    - name: Docker build and push
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker build -t maxhunt/shopping-cart:latest -f docker/Dockerfile .
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker push maxhunt/shopping-cart:latest
        
    - name: Deploy to Docker
      run: |
        docker run -d --name shop-shop -p 9070:9070 maxhunt/shopping-cart:latest
